use_frameworks!

platform :ios, '10.0'

target 'BNDDownPlaceBag_Example' do
  pod 'BNDDownPlaceBag', :path => '../'

  target 'BNDDownPlaceBag_Tests' do
    inherit! :search_paths
#    pod 'YTKNetwork'#, '3.0.0'
#    pod 'AFNetworking', '4.0.1'
  end
end
